# This workflow will run tests using node and then publish a package to GitHub Container Registry and Docker Hub Regitry when a pushed into main branches
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A

name: Continuous Integration

on:
  # Triggers the workflow on push events but only for the main branches
  push:
    branches:
      - develop
      - master
      - experimental
      - test/**
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - test/**
      - bugfix/**
      - feature/**

jobs:

  # Build dist application ADempiere-Proxy-Api
  build-app:
    name: Build dist ADempiere-Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Node configuration
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Copy default vue store front
        run: cp -rf ./packages/default-vsf ./src/modules/

      - name: Enable https to install packages
        run: git config --global url."https://".insteadOf git://

      - name: Install node dependencies
        run: yarn ci

      - name: Run test
        run: yarn lint

      - name: Compile dist
        run: |
          yarn build
          yarn prebuild:packages
  
      - name: Unit Test
        run: yarn test:unit

      - name: Copy template.json to deploy
        run: cp docker/adempiere-api/template.json config
        
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.3
        id: compress
        with:
          command: c
          cwd: .
          files: |
            config
            migrations
            scripts
            src
            var
            packages
            package.json
            ecosystem.json
            tsconfig.json
            nodemon.json
            graphql-schema-linter.config.js
            yarn.lock
          outPath: ./proxy-adempiere-api.tar.gz

      - name: Upload app as artifact
        uses: actions/upload-artifact@v3
        with:
          name: proxy-adempiere-api
          path: ./proxy-adempiere-api.tar.gz
